### ISSUE TITLE
Add a !version command

### ISSUE THREAD

**Issue by ItsPugle** [SamEm/Bug-Bot#26]
With a `!version <stable|ptb|canary|> <android|ios|windows|mac|linux>` command, it means that Bug Hunters™️ don't have to waste our time telling people to rather:

1. Check the pinned messages
2. Run a command that we pasted from #bug-hunter-general
3. Ask someone else

Let's say User A (Generic#1234) has a bug, and is asking in #general-chat for how to get the version number. Bug Hunter A (BugBuster#4321) is online and asks:
`What build are you on, and what Operating System?`. Generic#1234 replies with ptb on windows. BugBuster #4321 then runs `!version ptb windows` and it outputs the most recent version of the Windows PTB build.

Magic ✨

**Comment by Alkali-Metal** [comment]
Or, we could have the command output something like:
```
[Alkali#7806] !version pc
[BugBot] Here's how you can find your version on the PC and web versions of Discord!
Option 1: Check the numbered file in the "%appdata%/discord" (or "discordptb" / "discordcanary" depending on which build you found the bug on!)
Option 2: <Javascript thing from #Bug-Hunter-General>

[SomeDude#0000] !version mobile
[BugBot] Here's how you can find the version you are running on mobile Discord!
<And have the ways to find it on the mobile apps>
```

or if you wanted to get even more advanced, you could have it auto-detect what channel they are posting it in then tell them accordingly, so running it in #android-general would auto-return the mobile response.

With the syntax I suggested this would be fine, but with the syntax you suggested and the way you suggested it function, I would not like this command, it would be bad for the accuracy of the reports the way you suggested it.

**Comment by ItsPugle** [comment]
I agree @Alkali-Metal. Let's use your idea instead, hey?

**Comment by Alkali-Metal** [comment]
Sure, the syntax and way it would function would definitely have to be fleshed out more before it could really be integrated but other than that I feel like it's pretty solid.

**Comment by nullpixel** [comment]
this would be trivial to do by scraping canary datamining

**Comment by Alkali-Metal** [comment]
Oh, by no means would it be complicated, but we don't want people uselessly running a command to find out what the latest version is, we want to know what version THEY are on, because they might for some reason have not updated somehow and are on a different build number or version entirely, the actual reasoning behind not getting it on a variable response is so that the users themselves learn how to find their own version number instead of relying on a bot to tell them the latest version. When they may not actually be on the latest version.

**Comment by advaith1** [comment]
tbh we can just have a command that links to https://howtodiscord.tk/bugs/version, it has all the information.

**Comment by Tarek1337** [comment]
Or people read the pins? I don't get the point of  this, sorry.

**Comment by advaith1** [comment]
the pins doesn't have comprehensive info, though; it only has instructions for Windows, and even that is the version number, not build number. People want to know how to get the build number, and also the mobile version number, which are all on the page I linked.

**Comment by ItsPugle** [comment]
Based on the discussions in this thread, and the general suggestions of how to deal with this, I think that this is pointless (or at least, not beneficial in the long-run) anymore. Closed 😄
