### ISSUE TITLE
Report disapiared

### ISSUE THREAD

**Issue by Test83318** [SamEm/Bug-Bot#31]
![](https://hammerandchisel.zendesk.com/attachments/token/SqQvqsJUA7OnOahH0LmP0OTHT/?name=P.png)

**Comment by Tarek1337** [comment]
What are you reporting exactly?

**Comment by ThaTiemsz** [comment]
1. Disappeared.
2. This repo is no longer used as Bug-Bot will be completely rewritten, in any way you should use the server for these type of issues.
3. This isn't even an issue. Tarek could reproduce, then changed his stance to could not reproduce. His stance message was changed.
